### DISCUSSION TITLE
Standard Src Field Mapping for all pods

### DISCUSSION THREAD

**Discussion by Harshita-mindfire** [dendronhq/dendron#2431] [RFCs/Ideas]
This is the discussion for RFC [Standard Src Field Mapping for all pods](https://github.com/dendronhq/dendron-docs/blob/main/vault/rfc.44-standard-src-field-Mapping-for-all-pods.md).

**Comment by hikchoi** [comment]
Thank you for starting the thread.

Reposting a relevant discussion point that came up in https://github.com/dendronhq/dendron/issues/2410 : 

***

> this isn't actually an error though. when we export tags, the pod **should** read all tags. or if its not, its something we should discuss the behavior for in [[Standard Src Field Mapping for All Pods|dendron://private/task.2022.01.23.standard-src-field-mapping-for-all-pods]]

I would argue that it ___should not___.

The existence of frontmatter tags gives an affordance that says: _"here is where you should put all the tags"_.

Then the counter question as a user would be, _"why would tags in the body be mapped when I have explicitly set my tags in the frontmatter?_

Wouldn't it be better to explicitly state in the frontmatter that I want these tags to be used in the source field mapping rather than looking at all tags in the NoteProps?

Consider this case:

I have a task note. It's a fictional task to refactor my notes. I jot down some ideas for how to organize tags for my personal notes.
I have set some tag to categorize this task in frontmatter.

Some of my sentences in this note will look like this:

- _#scope.recipe is too big of a catchall. I should make this better_
- _The number of notes with #scope.undefined is getting out of hands. I need to give them a proper scope!_
- _These notes should not be in #scope.finance: [...]_

Should these use of hashtags be mapped to Airtable?

It's a made up case, but it illustrates my point: 

As-is, the success of export depends on the integrity of all the tags used in the note body, if any of the tag is entirely or partially part of the source field mapping defined by the pod. This limitation (or the lack of) is steering the user to write a note in a certain way that is not obvious, but the feature that is forcing the user to do so has no part in aiding the creation of note content. There is both immediate cost (non-zero cost writing / making sure it can export) and deferred cost (surprises down the line when I realize these exported notes do _not_ look like what I expected to be in the destination) in the export pod behaving like so.

With the export pod defining source field mapping, I am basically now blocked from using those tags in my body if I don't want this to happen. 

This goes for both valid, existing tags and non-existent ones as well.

- If it's a tag that is srcFieldMapped, and a singleTag field, it will hit an error because I already have one in frontmatter and just mentioned it again in the body.
  - e.g. try adding this sentence to any of our tasks: `Maybe we can do X here, but this would be out of scope. Let's create a new task to follow up. as a #sprint.next item.`. It won't if this task note itself already has a sprint tag in frontmatter.

- If it's a tag that doesn't exist yet, you can't even mention them if it's under any tag hierarchy that has been source field mapped. because Airtable doesn't know about these tags and refusing them.

One could argue that I can just escape the hashtag or just not make it a tag (just use wikilinks). That is indeed one solution, but it's not zero-cost. and it leaves the users wondering. It's preventing me from writing notes in a certain way.

**Reply by hikchoi** [reply]
@kevinslin 's response to this:

***

I think there is value in supporting both cases.  The way we can support that with frontmatter mapping is by limiting the scope in the "to" filed

```yml
# pull tags from anywhere in the note
Scope: {to: "all", type: "multiSelect", filter: "tags.scope.*"}
# pull tags from the frontmatter
Scope: {to: "fm.tags", type: "multiSelect", filter: "tags.scope.*"}
# pull tags from the body
Scope: {to: "body", type: "multiSelect", filter: "tags.scope.*"}
# pull tags from a specific section in the body
Scope: {to: "body#section1", type: "multiSelect", filter: "tags.scope.*"}
```
