### DISCUSSION TITLE
How to add custom CSS to dendron preview ?

### DISCUSSION THREAD

**Discussion by akharrou** [dendronhq/dendron#3010] [Q&A] [answered]
Following this doc page: https://wiki.dendron.so/notes/0fbg5vbv5jzb0623pbi4v3t/

I modified `dendron.yml` by adding `theme: custom` under the `preview` field, and added a `custom.css` file with the given example, then reloaded dendron preview and nothing happened.

```
.
├── custom.css
├── dendron.code-workspace
├── dendron.yml
└── notes
    ├── assets
    ├── root.md
    └── root.schema.yml

2 directories, 5 files
```

with the following `dendron.yml`:

```yaml
...
preview:
    theme: custom
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    automaticallyShowPreview: false
...
```

with the following `custom.css`:

```css
body {
  /* The background color of the preview. */
  background-color: #fff;
}

body,
h1,
h2,
h3,
h4 {
  /* Text color for the text, not including links. */
  color: #ffffff;
}

a,
a:hover,
a:active {
  /** Color for links, except ones that have been already visited. */
  color: #b2f7ef;
}
```
