### DISCUSSION TITLE
glob/ignore parent path when applying a schema

### DISCUSSION THREAD

**Discussion by danieleades** [dendronhq/dendron#3837] [Q&A]
I would like to apply a meeting template to any document whose path contains `*.meet.[0-2][0-9][0-9][0-9].[0-1][0-9].[0-3][0-9]`, but i don't care about the root.

I would like to have multiple 'project' namespaces, but a single 'meeting' template.

eg.

- `project-a.meet.2022.12.05.md`
- `project-b.meet.2022.12.05.md`
- `project-c.meet.2022.12.05.md`

Is there some way to achieve this?

i've tried a schema like the following (without success)

```yaml
version: 1
schemas:
  - id: meet
    parent: root
    children:
      - pattern: '*'
        children:
        - pattern: meet
          children:
            - pattern: "[0-2][0-9][0-9][0-9]"
              children:
                - pattern: "[0-1][0-9]"
                  children:
                    - pattern: "[0-3][0-9]"
                      template: templates.meet
```

i've also tried this-

```
version: 1
schemas:
  - id: '*'
    parent: root
    children:
      - pattern: meet
        children:
          - pattern: "[0-2][0-9][0-9][0-9]"
            children:
              - pattern: "[0-1][0-9]"
                children:
                  - pattern: "[0-3][0-9]"
                    template: templates.meet
```

I *was* able to get the following similar pattern to work - `project.*.meet.[0-2][0-9][0-9][0-9].[0-1][0-9].[0-3][0-9]`

using this schema-

```
version: 1
schemas:
  - id: 'project'
    parent: root
    children:
      - pattern: '*'
        children:
        - pattern: meet
          children:
            - pattern: "[0-2][0-9][0-9][0-9]"
              children:
                - pattern: "[0-1][0-9]"
                  children:
                    - pattern: "[0-3][0-9]"
                      template: templates.meet
```

any help would be greatly appreciated
