### DISCUSSION TITLE
12 - Schema Improvements

### DISCUSSION THREAD

**Discussion by ghost** [dendronhq/dendron#727] [RFCs/Ideas]
This place is meant as Discussion place for the Schema Improvements rfc.

Tracking Issue: #712 
Rfc Document: https://wiki.dendron.so/notes/8bc80164-6436-4c77-8077-7842f53a4a23.html

Please create a Separate comment/ response for each part of the Rfc to make it easier to navigate the Opinions about the Separate parts of the RFC.

**Comment by xeor** [comment]
Is some of the ideas from https://github.com/dendronhq/dendron/issues/745 worth adding to the RFC?

**Reply by ghost** [reply]
Honestly, I like the idea of actions, but one question I immediately get is, will a Schema have only one action, or could it have more? 
- If it can have more maybe the command could show all schemas with defined actions as well as letting you type on the selection of a schema it shows all actions of that schema.
Secondly, how reusable should these Actions be?
- I mean your example could be used for every Journal schema out there, but to make it easier to improve on this we may want to declare that if the action is defined on a Schema that becomes the child of another schema that the Patter / Id gets added to the schema. 
  ```yml
  version: 1
  schemas:
  - id: journal
    desc: Journal notes
    action:
      variables:
        - name: "name"
           type: "text"
           default: ""
           msg: "What should the note suffix be?"
      # Must match pattern
      name: "journal.%Y.%M.%D $name$"
  -id: projects
    namespace: true
    children:
      - journal
  ``` 
  That this would result in "projects.foo.journal.2020.01.01.$Name" 
  
Thirdly,  Could an action be extended, by providing additional Variables and changing the result?
- Either adding an additional prefix or sufix

In Relation to the Rfc I would Probably think about adding actions as a Type.
