### ISSUE TITLE
Option to Label Daily Journal as Journal

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#1040]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [X] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Less of a bug report, more of a question.

Prior to Dendron 0.51.0, I was able to create daily journal notes with the following naming convention: `journal.y.MM.dd`.

With the update to Dendron 0.51.0, this ceased to work. I emptied the deprecated journal note fields in the VS Code settings, and attempted to restore the old setup in my dendron.yml. I have not been successful.

My dendron.yml setup is currently as follows:

```
journal:
    dailyDomain: journal
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomain
    firstDayOfWeek: 1
```

If I leave `dailyDomain` empty then I am unable to create daily journal notes at all.

If I leave `name` empty then I am able to create daily journal notes with the naming convention: `journal.y.MM.dd`, but:
1. The title field in the frontmatter is not filled correctly.
2. I can no longer create journal notes with the naming convention: `{domain}.journal.y.MM.dd`. 

I have combed through the Dendron site this past week, but I have been unable to find a setting for the dendron.yml that would replicate the old set up. 

Is there an option to label daily journal notes as just "Journal" at this time? 

Thank you.

**Comment by hikchoi** [comment]
This should work 🙂 

```
journal:
    dailyDomain: journal
    name: journal
    dateFormat: y.MM.dd
    addBehavior: asOwnDomain
    firstDayOfWeek: 1
```

Please let me know if it doesn't.

**Comment by micharris42** [comment]
Thank you for the suggestion. I have updated my my dendron.yml, and this has fixed issue 1. I am able to create daily journal notes with the naming convention `journal.y.MM.dd` and the frontmatter is being filled in correctly.

However, issue 2 remains unresolved. I still cannot create journal notes with the naming convention '{domain}.journal.y.MM.dd'. Trying to use the feature, regardless of the current domain, automatically fills in the note title as `journal.y.MM.dd`.

Is there a way to restore this functionality? Or is that not possible at this time? 

Thank you.

**Comment by micharris42** [comment]
Giving this issue a bump.

With the release of [Dendron 0.93](https://wiki.dendron.so/notes/nwnxrcwwj58goq80hrdm0la/), the Calendar View has been enabled in my vault for the first time.

With my current dendron.yml setup:

```
journal:
    dailyDomain: journal
    name: journal
    dateFormat: y.MM.dd
    addBehavior: asOwnDomain
```

Using the Calendar View generates journal notes with the title format of `journal.journal.y.MM.dd`. For example, `journal.journal.2022.05.03`. This is despite my already having a journal note of `journal.2022.05.03`, created through the default Dendron command of `Ctrl+Shift+I`.

At the moment, these two methods for creating journal notes, the Calendar View and the lookup command, are not in agreement.

Please let me know if this should be spun of as its own issue.

Thank you.
