### ISSUE TITLE
Help with journal.schema.yml using journal.template.daily.md

### ISSUE THREAD

**Issue by ericthomas1** [dendronhq/dendron#1077]
I like using `CTRL+SHFT+I` to create daily journal entries. I've created a `journal.template.md` file that I want to use. I've added the template to `journal.shema.yml` but it never loads into a new journal entry. 

**Can someone spot what I'm missing?**

`journal.schema.yml`

```
version: 1
schemas:
- id: journal
  title: journal
  desc: ""
  parent: root
  children:
    - daily
    - weekly
    - yearly
- id: daily
  namespace: true
  template:
    id: journal.template.daily.md
    type: note
- id: weekly
  namespace: true
- id: yearly
  namespace: true
```

`journal.template.daily.md`

```
##### Login:        
##### Logout:       
##### Duration:     

##### Skills and tools used:

| Skill/Tool/Language | Notes                |
| ------------------| ------------------      |
| VS Code             | Always!                    |
| Markdown         | Daily work journal    |
| Dendron             | Daily work journal   |

##### To-do List:


##### Context:


##### TIL's:


##### Big News:
```

**Comment by jonathanyeung** [comment]
Hi @ericthomas1 - thanks for the feedback. 

Can you try removing the `.md` suffix from the template id? 

```markdown
  template:
    id: journal.template.daily
```

Schemas and Templates are a bit hard to work with right now - we are thinking of ways to make them easier to set up. Appreciate the patience

**Comment by jonathanyeung** [comment]
I just tried to make my own schema following a similar daily pattern and it took me over an hour to debug before it finally worked 😅. It's definitely a user pain point that we'll try to address. 

I think more changes need to be made to your `journal.schema.yml`.  Can you try this instead?

```yaml
version: 1
imports: []
schemas:
  - id: journal
    title: journal
    desc: ""
    parent: root
    children:
      - year
  - id: year
    title: year
    pattern: "[0-2][0-9][0-9][0-9]"
    children: 
      - month
  - id: month
    title: month
    pattern: "[0-9][0-9]"
    children:
      - day
  - id: day
    title: day
    pattern: "[0-9][0-9]"
    template:
      id: journal.template.daily
      type: note
```

Explanation - the `Ctrl+Shift+I` daily journal follows a format with a pattern of `daily.journal.2021.08.10`, whereas in your example, it should work for a note formatted like `journal.daily.2021-08-10`.  The difference (besides the ordering of `daily` vs `journal` is the `-` delimiter vs using the `.` delimiter. A dash doesn't create a new hierarchy, whereas a period does. 

Let me know if this works. I realize it's confusing because in Kevin's tutorial video [here](https://www.loom.com/share/481b7ab051394c1caa383383bd265755), you'll notice his notes are formatted like  `journal.daily.2021-08-10`, which is not the format the built in daily journal command follows.  We'll try to clean up our documentation.
