### ISSUE TITLE
Logo and site name when published, does not apply consistently across pages

### ISSUE THREAD

**Issue by nz-john** [dendronhq/dendron#1236]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

"Logo and site name when published, does not apply consistently across pages."
- not cached. happens on "private browsing" / "new private window"

## To Reproduce

1. publish site with: `npx dendron buildSite  --stage dev --serve`
2. view site with "new private window" (to ensure not caching) in Google Chrome
3. see that root page (and some content pages also) has the logo and site title applied correctly
4. see that other pages have link-text `Dendron` where logo should be, and search bar says: "Search Dendron" instead of "Search <site_name>"

## Expected behavior

"When published, the logo and site name should have applied consistently to every page?"

## Screenshots

![brave_y8Sm4gdJqD](https://user-images.githubusercontent.com/89765379/131291502-11e294ac-c41b-4360-bad0-688380bf734a.png)
![brave_v5pjPODcet](https://user-images.githubusercontent.com/89765379/131291510-bd95d345-d911-4aee-a71d-01b68abe741b.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: Brave + Chrome
- Version:
![chrome_Fx4kqJmm0C](https://user-images.githubusercontent.com/89765379/131291662-ac74ee92-c2f0-4a6c-8107-016074688baf.png)

## Additional context

`dendron.yml`

```yml
version: 1
vaults:
    -
        fsPath: j
useFMTitle: true
useNoteTitleForLink: true
noAutoCreateOnDefinition: true
noLegacyNoteRef: true
noXVaultWikiLink: true
lookupConfirmVaultOnCreate: false
mermaid: true
useKatex: true
autoFoldFrontmatter: false
dev:
    enablePreviewV2: true
lookup:
    note:
        selectionType: selectionExtract
journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfCurrent
    firstDayOfWeek: 1
scratch:
    name: scratch
    dateFormat: y-MM-dd-HHmmss
    addBehavior: childOfCurrent
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    usePrettyRefs: true
    title: J
    description: Private knowledge space
    logo: "/j/assets/images/logo.png"
initializeRemoteVaults: true
dendronVersion: 0.56.0
noTelemetry: true
noRandomlyColoredTags: true
```
