### ISSUE TITLE
First list element of siteHierarchies can't be vault referenced.

### ISSUE THREAD

**Issue by ghost** [dendronhq/dendron#1506]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

First list element of  siteHierarchies can't be vault referenced.

## To Reproduce

1. Create two or more vaults.
2. Open dendron.yml.
3. Refrence the vault of the first element in `siteHierarchies`

E.g. this doesn't work:

```yml
site:
    siteHierarchies:
        - Rezepte.spiel
        - vault.tutorial
        - Clothes.clothing
```

while this works:
```yml
site:
    siteHierarchies:
        - spiel
        - vault.tutorial
        - Clothes.clothing
```

## Expected behavior

Publish the hierarchy
## Desktop (please complete the following information)

- OS: [Windows / Linux]
- Version 0.62.3

## Additional context

This has the big disadvantage that the first hierarchy entry you plan to publish and use as index has to be unique among all your vaults.

## Dendron Log file

```
Error: no site index found
    at getNotes (C:\Users\v\AppData\Roaming\npm\node_modules\@dendronhq\dendron-11ty-legacy\_data\notes.js:41:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async buildNav (C:\Users\v\AppData\Roaming\npm\node_modules\@dendronhq\dendron-11ty-legacy\bin\build-nav.js:56:28)
    at async Promise.all (index 0)
    at async BuildSiteV2CLICommand.execute (C:\Users\v\AppData\Roaming\npm\node_modules\@dendronhq\dendron-cli\lib\src\commands\build-site-v2.js:117:9)
    at async Object.CLICommand.eval [as handler] (C:\Users\v\AppData\Roaming\npm\node_modules\@dendronhq\dendron-cli\lib\src\commands\base.js:41:25)
```
