### ISSUE TITLE
Custom markup for tags when rendered in the markdown preview

### ISSUE THREAD

**Issue by d3vr** [dendronhq/dendron#155]
**Is your feature request related to a problem? Please describe.**
Right now tags are just rendered as text in the markdown preview, so we can't really customize how they look in the preview. 

**Describe the solution you'd like**
It would be great if they're wrapped with a `span`, something like: 
```html
<span class="tag" data-tag="books">#books</span>
```
This way we can add css customisations like:
```css
.tag {
    padding: 3px;
    border-radius: 5px;
}

.tag[data-tag="books"] {
    background: blue;
}
```

**Describe alternatives you've considered**
For now I'm just wrapping tags in an inline code block so they look slightly better, but that doesn't really solve the "problem".

**Additional context**
I feel like it's just a visual improvement and shouldn't be high priority, but would be great to have nonetheless

**Comment by aleksey-rowan** [comment]
Hey, @d3vr, you can do this now with [Dendron's preview themes](https://wiki.dendron.so/notes/lb9wd7z62ch7b4slscp05i4/):

- enabled custom preview theme by setting it in `dendron.yml`
  ```yml
  preview:
    theme: custom
    ...
  ````
- create `custom.css` file at the root of your workspace
- style tags however you want
  ```css
  a.color-tag {
      padding: 3px 5px;
      border: 1px;
      border-radius: 3px;
      background: blue;
  }
  
  a.color-tag[href='tags.books'] {
      background: grey;
      border-radius: 0;
  }
  ```
  - enjoy the garish colours :D
  ![image](https://user-images.githubusercontent.com/79934725/179818164-4bb7a0a8-334a-430c-8834-64dfe6912383.png)

**Note:** When using a custom theme, it no longer adapts to the current VSCode theme. This issue is tracked in https://github.com/dendronhq/dendron/issues/3138.

Does this solve the problem for you?
