### ISSUE TITLE
Update default schema 

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#158]
## Context
The default schema that Dendron creates when user's do a **Schema Lookup** is not up to date with the latest [schema version](http://dendron.so/notes/c5e5adde-5459-409b-b34d-a0d75cbb1052.html#schema-anatomy).

Current schema:
```yml
-
    id: foo
    title: foo
    desc: ""
    parent: root

```

Latest schema :
```yml
version: 1
schemas:
-
    id: foo
    title: foo
    desc: ""
    parent: root

```

## Proposal
Initialize new schemas with the latest schema template
