### ISSUE TITLE
prompting error abt lang.schema.yml in v0.68.1

### ISSUE THREAD

**Issue by simkimsia** [dendronhq/dendron#1699]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

After i upgrade to v0.68.1 i start getting this error

![image](https://user-images.githubusercontent.com/245021/141389710-aca5640a-dcd0-4324-a26b-4d22d487b717.png)

it wasnt like that before.

if i delete `data` then i get naohter error abt sections

![image](https://user-images.githubusercontent.com/245021/141389783-d73cbe43-b36c-4c1d-bd1b-8e2ebf76d7c9.png)

my lang.schema.yml is as below:

```
version: 1
schemas:
- id: lang
  title: language
  desc: programming language
  parent: root
  pattern: lang
  data:
    namespace: true
  children:
    - operator
    - d
    - flow
    - lib
    - dev
    - t
    - files
    - oo
    - func
    - types

# --- operator
- id: operator
  children:
    - comment
    - create
    - compare
    - equal
    - scope
    - inspect
    - format
    - iterate
    - destructure
- id: comment
- id: create
- id: compare
- id: equal
  sections:
    - value
    - reference
- id: scope
- id: inspect
- id: format
- id: iterate
- id: destructure
  sections:
    - array
    - obj

# --- data
- id: d
  title: data structure
  children:
    - boolean
    - string
    - array
    - dict
    - csv
    - json
    - set
    - validation
    - iterator
- id: validation
  desc: "runtime validation of data"
- id: boolean
- id: string
  children:
    - regex
- id: regex
- id: set
- id: array
- id: dict
  children:
    - defaultdict
- id: defaultdict
- id: csv
- id: json
- id: iterator

# --- dev
- id: dev
  desc: "dev stuff"
  children:
    - dev.lib
    - migration
    - runtime
    - mode
- id: files
  children:
    - io
    - path
  sections:
  - zip
  - nav
- id: path
- id: runtime
  desc: "java, .net, etc"
- id: lib
  namespace: true
- id: import
  sections:
  - dynamic
  - reload

# --- deb.lib
- id: "dev.lib"
  title: lib
  pattern: lib
  children:
    - publish
    - binary
    - import
    - export
    - dynamic
- id: dynamic
  desc: dynamically inspecting and modifying lib
- id: publish
- id: binary
  desc: how to create executable binaries
- id: export
# --- topics
- id: t
  title: topic
  children:
    - system
    - net
    - time
    - image
- id: image
- id: net
  title: network
- id: system
  children:
    - uuid
    - cli
    - shell
- id: shell
  desc: execute shell commands
  sections:
    - env
    - exec
    - fork
    - eval
- id: cli
  desc: generate cli interface
- id: uuid
- id: exec
  desc: "executing system comm"
- id: io
- id: migration
- id: mode
  desc: |
    eg. 'strict' mode in javascript

# --- oo
- id: oo
  title: object oriented
  children:
    - scope
    - inheritance

- id: scope
  sections:
    - public
    - protected
    - private

- id: inheritance

# --- func
- id: func
  title: functional
  sections:
    - positional
    - varargs
    - keyword
    - mixed
    - defaults

# --- flow
- id: flow
  sections.children:
    - ternary
  children:
    - if
    - while
- id: if
- id: while

# --- types
- id: types
  children:
    - generics
    - modifiers
    - union
    - intersection
    - interface
- id: generics
- id: modifiers
  sections:
    - partial
    - readonly
- id: union
- id: intersection
- id: interface

# --- time
- id: time
```

## To Reproduce

SEe above
## Expected behavior

no error message

## Screenshots

see above

## Desktop (please complete the following information)

version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T09:23:14.144Z (6 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

## Additional context
none

## Dendron Log file

```
{"level":30,"time":1636677977688,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1636677977784,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/kim/Library/Application Support/Code/logs/20211112T084606/exthost1/dendron.dendron","extensionPath":"/Users/kim/.vscode/extensions/dendron.dendron-0.68.1","extensionUri":"/Users/kim/.vscode/extensions/dendron.dendron-0.68.1","workspaceFile":"/Users/kim/Dendron/dendron.code-workspace","workspaceFolders":["/Users/kim/Dendron/vault"]}
{"level":30,"time":1636677977785,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1636677977785,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636677977786,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636677977786,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636677977799,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1636677977800,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.68.1","previousWorkspaceVersion":"0.68.1","previousGlobalVersion":"0.68.1","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1636677977812,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1636677977812,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636677977812,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636677977812,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636677977813,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1636677977813,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Segment Residual Cache Path is at undefined"}
{"level":30,"time":1636677978123,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636677978123,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636677978124,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636677978124,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1636677978124,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Segment Residual Cache Path is at /Users/kim/Library/Application Support/Code/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1636677978124,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1636677978189,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","workspaceInstallStatus":"NO_CHANGE","currentVersion":"0.68.1","previousWorkspaceVersion":"0.68.1","previousGlobalVersion":"0.68.1","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml","version":"1.2.0","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1636677978197,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"execServer","state":"enter"}
{"level":30,"time":1636677978206,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1636677979422,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Segment Residual Cache flush attempted. {\"successCount\":0,\"nonRetryableErrorCount\":0,\"retryableErrorCount\":0}"}
{"level":30,"time":1636677981851,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1636677981852,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636677981853,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636677981853,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636677981869,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"execServer","state":"message","message":"56432"}
{"level":30,"time":1636677981876,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":89300}
{"level":30,"time":1636677981876,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","msg":"post-start-server","port":56432,"durationStartServer":4074}
{"level":30,"time":1636677981881,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/kim/Dendron","vaults":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1636677981885,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1636677981885,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1636677982038,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"daily","root":{"fsPath":"vault"}}
{"level":30,"time":1636677982042,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"framework","root":{"fsPath":"vault"},"imports":[]}
{"level":30,"time":1636677982052,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"lang","root":{"fsPath":"vault"}}
{"level":30,"time":1636677982055,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"pro","root":{"fsPath":"vault"}}
{"level":30,"time":1636677982083,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"weekly","root":{"fsPath":"vault"}}
{"level":30,"time":1636677982452,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":1,"noteRefsLength":0,"wikiLinksLength":1}
{"level":30,"time":1636677982609,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":8,"noteRefsLength":0,"wikiLinksLength":8}
{"level":30,"time":1636677982662,"pid":89300,"hostname":"kimsia-mbp-2014.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":8,"noteRefsLength":0,"wikiLinksLength":8}
{"level":30,"time":1636677982757,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":870}
{"level":50,"time":1636677982757,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","error":{"stack":"DendronError: Schema 'lang.schema.yml' is malformed. Reason: Detected invalid property \"data\" . Use 'Go to File...' command to resolve malformed schema.\n    at d.init (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/server.js:2:192053)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async c.init (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/server.js:2:12513)\n    at async /Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/server.js:2:19102","message":"Schema 'lang.schema.yml' is malformed. Reason: Detected invalid property \"data\" . Use 'Go to File...' command to resolve malformed schema.","name":"DendronError","status":"unknown","severity":"minor","payload":"\"{\\\"schema\\\":{\\\"name\\\":\\\"DendronError\\\",\\\"status\\\":\\\"unknown\\\",\\\"payload\\\":\\\"[{\\\\\\\"name\\\\\\\":\\\\\\\"DendronError\\\\\\\",\\\\\\\"status\\\\\\\":\\\\\\\"unknown\\\\\\\",\\\\\\\"payload\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"fpath\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"lang.schema.yml\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"Detected invalid property \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"data\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"cause\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"name\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"DendronError\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"status\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"unknown\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"severity\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"minor\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"payload\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"{}\\\\\\\\\\\\\\\"}}\\\\\\\"}]\\\"}}\""},"msg":"init error"}
{"level":30,"time":1636677982775,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1636677982775,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1636677982779,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1636677982779,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1636677982780,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1636677982780,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1636677982781,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1636677982804,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1636677982807,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1636677982815,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1636677982891,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updateDecorations","msg":"Displaying 0 warnings and 2 decorations"}
{"level":30,"time":1636677982894,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1636677982894,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":5006}
{"level":30,"time":1636677982894,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.68.1","previousExtensionVersion":"0.68.1"}
{"level":30,"time":1636677982896,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1636677998329,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kim/Dendron/vault/24-48-7.24.guide-domains.md"}
{"level":30,"time":1636677998350,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updateDecorations","msg":"Displaying 0 warnings and 1 decorations"}
{"level":30,"time":1636677998688,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kim/Dendron/vault/weekly.journal.2021.W45-11-08-to-11-14.md","/Users/kim/Dendron/vault/lang.schema.yml"]}
{"level":30,"time":1636677998689,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kim/Dendron/vault/lang.schema.yml"}
{"level":30,"time":1636677998695,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onFirstOpen","msg":"enter","fname":"lang.schema.yml"}
{"level":30,"time":1636677999530,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onFirstOpen","msg":"exit","fname":"lang.schema.yml"}
{"level":30,"time":1636678012008,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/kim/Dendron/vault/lang.schema.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1636678012028,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"SchemaSyncService:onDidChange","msg":"updating schema."}
{"level":30,"time":1636678012030,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"parse","msg":"enter","fpaths":["lang.schema.yml"],"vault":{"fsPath":"vault"}}
{"level":30,"time":1636678012040,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"lang","root":{"fsPath":"vault"}}
{"level":30,"time":1636678080025,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kim/Dendron/vault/weekly.journal.2021.W45-11-08-to-11-14.md"]}
{"level":30,"time":1636678080026,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1636678167645,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kim/Dendron/vault/weekly.journal.2021.W45-11-08-to-11-14.md"}
{"level":30,"time":1636678167683,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updateDecorations","msg":"Displaying 0 warnings and 2 decorations"}
{"level":30,"time":1636678195650,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kim/Dendron/vault/lang.schema.yml"]}
{"level":30,"time":1636678195652,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kim/Dendron/vault/lang.schema.yml"}
{"level":30,"time":1636678203036,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/kim/Dendron/vault/lang.schema.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1636678203050,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"SchemaSyncService:onDidChange","msg":"updating schema."}
{"level":30,"time":1636678203051,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"parse","msg":"enter","fpaths":["lang.schema.yml"],"vault":{"fsPath":"vault"}}
{"level":30,"time":1636678203059,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"lang","root":{"fsPath":"vault"}}
{"level":30,"time":1636678276824,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1636678276826,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1636678276861,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1636678277452,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kim/Library/Application Support/Code/logs/20211112T084606/exthost1/dendron.dendron/dendron.log"]}
{"level":30,"time":1636678277453,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kim/Library/Application Support/Code/logs/20211112T084606/exthost1/dendron.dendron/dendron.log"}
{"level":30,"time":1636678277454,"pid":89278,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","uri":"/Users/kim/Library/Application Support/Code/logs/20211112T084606/exthost1/dendron.dendron/dendron.log","msg":"not in workspace"}

```
