### ISSUE TITLE
Schema Graph doesn't handle wildcard as expected

### ISSUE THREAD

**Issue by flatrick** [dendronhq/dendron#1775]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Using wildcards in a pattern is shown as random strings of alphanumeric values in the Schema Graph.

## To Reproduce

1. Add the following to a schema:
```yaml
  - id: misc
    title: Unsorted notes
    desc: "Notes without category"
    namespace: true
    template:
      id: templates.pkm
      type: note
    children:
      - pattern: "**/*"
```
2. CTRL+SHIFT+P
3. `Dendron: Show Schema Graph`
4. Look at the node corresponding to the wildcard (`*` also gives the same result as `**/*`)

## Expected behavior

The title set in the schema should be shown instead of the random string

## Screenshots

![image](https://user-images.githubusercontent.com/5464311/143037614-faf1b946-d74f-4003-a974-4009f060855a.png)

## Desktop (please complete the following information)

- OS: Windows 10
- VSCode: 1.62.3
- Dendron: 0.69.1
