### ISSUE TITLE
Schema nodes cannot be reused in two parents in schema hierarchy.

### ISSUE THREAD

**Issue by maximilianigl** [dendronhq/dendron#1799]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [X] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Re-using schemas in a hierarchy doesn't work, i.e. having the same `id` appear in two different parents, will only match the later defined parent.

## To Reproduce

1. Create example `testSchema.schema.yml`:

```
version: 1
schemas:
  - id: testSchema
    children:
      - child1
      - child2
    title: testSchema
    parent: root
  - id: child1
    children:
      - sharedGrandchild
  - id: child2
    children:
      - sharedGrandchild

  - id: sharedGrandchild
    template: template.test
```

2. Create some `template.test`.
3. Create note `testSchema.child1.sharedGrandchild` -> **No template applied**
4. Create note `testSchema.child2.sharedGrandchild` -> **Template *is* applied**

## Expected behavior

Template should be applied in both above cases.

## Desktop (please complete the following information)

- OS: iOS
