### ISSUE TITLE
Ability to add external links to the left-hand nav / table of contents (TOC)

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#1829]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

There are some links that would be helpful to exist in the TOC, because they are then available to the reader on any page they are viewing. For example: I'd like to link to the GitHub repo of the source docs, or to other related docsets.

## Describe the solution you'd like ##

Allow a way (perhaps in the `dendron.yml` under `site` somewhere?) to extend the left-hand TOC to include external links (Contributor Docs, GitHub Repo, related docsets)? For example: When looking at the [`furo` Sphinx theme](https://pradyunsg.me/furo/quickstart/), they distinguish external links in their TOC with a little icon. It would ensure that the link is always visible?

![image](https://user-images.githubusercontent.com/5951023/144480986-88339f0d-4312-4482-9682-c892b6995886.png)

Could look something like this in implementation:

```yml
site:
  externalLinks:
    github-repo:
      name: 'GitHub Repository'
      url: 'https://github.com'
```

## Describe alternatives you've considered ##

Markdown formatted links in the `siteHierarchies` list?

```yaml
site:
  siteHierarchies:
    - subjects
    - blog
    - [GitHub Repo](https://github.com)
```
