### ISSUE TITLE
Help: Schema with multi-level alphanumeric patterns

### ISSUE THREAD

**Issue by AdamWorley** [dendronhq/dendron#1962]
Hi I've been trying to get a multi-level wildcard schema structure working but I can't seem to find a pattern that works.

I'm trying to get something like the following structure:
- review.book.{author}.{name-of-book}
- review.tv.{creator}.{name-of-show}
- review.film.{director}.{name-of-film}

where each one would be able to use a review template.

I am able to get the schema working if I use the number range pattern (i.e. `[0-9]`) so for example `review.tv.1.2` works correctly.

If I try to use the wildcard (*) for the pattern however nothing seems to match. I wondered if maybe that was being too greedy and including any periods in the name structure so tried using [[:alpha:]] and [[:alnum:]], but it seems maybe these aren't valid patterns in dendron?

I've tried various, levels of setting `namespace: true` but have been unable to find a method that works using that either.

I've included what have for the schema at the moment below and would really appreciate any help with this!

Thanks in adavance!

``` yml
version: 1
imports: []
schemas:
  - id: review
    title: review
    parent: root
    children:
      - film
      - tv
      - book
  
  - id: film
    title: film
    children:
      - director
  - id: director
    title: director
    pattern: "*"
    namespace: true
    template:
      id: review.template
      type: note

  - id: book
    title: book
    children:
      - author
  - id: author
    title: author
    pattern: "*"
    namespace: true
    template:
      id: review.template
      type: note
  
  - id: tv
    title: tv
    children:
      - creator
  - id: creator
    title: creator
    pattern: "[0-9]"
    desc: the creator of the show
    children:
      - entry
  
  - id: entry
    title: entry
    pattern: "[0-9]"
    namespace: true
    template:
      id: review.template
      type: note
```

**Comment by jonathanyeung** [comment]
Hi @AdamWorley - you can give our inline schemas syntax a try - it's a bit easier to work with, as the `namespace` field can be a little confusing to work with.  I tested this locally, this should work:

```yaml
version: 1
imports: []
schemas:
  - id: review
    title: review
    parent: root
    children:
      - pattern: film
        children:
          - pattern: '*'
            children:
              - pattern: '*'
                template: review.template
      - pattern: tv
        children:
          - pattern: '*'
            children:
              - pattern: '*'
                template: review.template
      - pattern: book
        children:
          - pattern: '*'
            children:
              - pattern: '*'
                template: review.template
```

Docs on inline schemas here: https://wiki.dendron.so/notes/c5e5adde-5459-409b-b34d-a0d75cbb1052/#inline-schema-anatomy
