### ISSUE TITLE
Frontmatter Variable Substitution Not Working When Inside a Schema Template

### ISSUE THREAD

**Issue by jonathanyeung** [dendronhq/dendron#2172]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

If you have a schema template that contains frontmatter variable substitution syntax, i.e. `{{ fm.title}}`, then when you try to create a new note with that schema template applied, the note won't get created with an error "fm is not defined".

## To Reproduce

1. Create a schema template note. Add {{ fm.title }} as contents.
2. Create a schema definition where a node applies that template
3. Try to create a note that matches that schema definition. (In example below, `book.test.notes`)

### Example files

`book.template.note.md`:
```markdown
...
# _{{ fm.title }}_ Reading Notes  
...
```

`book.schema.yml`:
```yml
version: 1
schemas:
- id: book
  title: book
  desc: ""
  parent: root
  namespace: true
  children:
    - notes
- id: notes
  pattern: "notes"
  template:
    id: book.template.notes
    type: note
```

## Expected behavior

Note gets created with FM variable substitution working.

## Desktop (please complete the following information)

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context

Bug is here: 

https://github.com/dendronhq/dendron/blob/c99ca019318cb451cd2a13a52fba2aefcb22a6d7/packages/common-all/src/dnode.ts#L1382

The data payload being passed to the `compiledSchemaTemplate` function doesn't have the frontmatter variables.

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
