### ISSUE TITLE
Workspace sync doesn't include workspace (only vaults)

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2208]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When running the command `Dendron: Workspace: Sync`, the vault git repositories are synced, but the workspace repository itself is not.

## To Reproduce

1. Create a multi vault setup with at least 2 repos like:
  - `workspace/.git`
  - `workspace/vault/.git`
2. Edit some files inside a vault
3. Edit the `dendron.code-workspace` or `dendron.yml` file
4. Run `Dendron: Workspace: Sync`
5. Note that your changes in `workspace/` have not been committed nor pushed

## Expected behavior

I expect the workspace sync command to sync my workspace as well as my vaults.

**Comment by hikchoi** [comment]
Thank you for the issue.

The name `Workspace: Sync` is a bit misleading;

This is a command that `Synchronizes all notes across all vaults with git.`, and is not a command that would sync the workspace itself.

Please take a look at https://wiki.dendron.so/notes/c4cf5519-f7c2-4a23-b93b-1c9a02880f6b/#workspace-sync

Do you think this should be support by this command? (or perhaps a separate command)? If so, let us know and we'll track it as a feature request rather than a bug. If the name is misleading, we can also discuss about making it clear.

it would be super awesome if you can amend this issue or create a separate one for a feature request, but otherwise we will be tracking them internally as such. Please let us know.

**Comment by aleksey-rowan** [comment]
Are you using remote or local vaults? If all your vaults are remote, `Workspace: Sync` will only sync them but not the workspace itself. As a workaround, you can add a local vault (just keep it empty) and the sync should pick up the workspace files as well.

**Comment by SeriousBug** [comment]
I'll be working on improving the sync this week, I'll make sure to consider how the workspace itself syncs too.

**Comment by chmac** [comment]
> Are you using remote or local vaults? If all your vaults are remote, `Workspace: Sync` will only sync them but not the workspace itself. As a workaround, you can add a local vault (just keep it empty) and the sync should pick up the workspace files as well.

Yes I am. That workaround sounds great, I'll do that. Thanks.

**Comment by chmac** [comment]
> Are you using remote or local vaults? If all your vaults are remote, `Workspace: Sync` will only sync them but not the workspace itself. As a workaround, you can add a local vault (just keep it empty) and the sync should pick up the workspace files as well.

Hmm, I just tried this, and it didn't work. I observed 2 things:

- Adding a new local vault put that vault's name into the workspace `.gitignore` - that means my vault is unversioned. Is that a bug? If so I can file a new issue.
- Even after I removed it from the `.gitignore` the sync command still did not sync my workspace (even though it now includes a local vault).

**Comment by aleksey-rowan** [comment]
I tried making it from scratch and there seems to be a small trick to it:

```text
// folder structure:

workspace/    // git@github.com:user/workspace-sync-test.git
  .git
  remote-vault/   // git@github.com:user/remote-vault-sync-test.git
    .git
  vault // local empty vault
```

```yml
# dendron.yml

workspace:
    vaults:
        - fsPath: vault
          sync: sync            <-- **this is the trick**
          name: vault

        - fsPath: remote-vault
          remote:
              type: git
              url: 'git@github.com:user/remote-vault-sync-test.git'
          name: remote-vault
```

You need to set `sync: sync` on the local vault. If `sync` value is not set, the workspace and the local vault files are not synced.

This is weird since `sync: sync` should be the default value for local vault, but it seems to be overrided by the [workspaceVaultSyncMode](https://wiki.dendron.so/notes/3i4ABJutl7NGeXRHTnUEC/#workspacevaultsyncmode) setting which defaults to 'noCommit'. If you change that to `sync`, it also works without setting `sync` on the vault itself. 

I'm not sure I'm getting this right, because as far as I understand `workspace vaults` are remote vaults that belong to a different workspace and why `workspaceVaultSyncMode` would affect syncing of local vaults and the local workspace files is unclear.

In any case, the above POC works.

**Comment by SeriousBug** [comment]
You are understanding it correctly. `workspaceVaultSync` affects the local vault because the local vault is part of a workspace, so Dendron thinks it's a workspace vault.

What it instead should do I think is to skip over any local vaults, and separately also sync the workspace. This should also have its own configuration, something like `workspaceSync`.

**Comment by voothi** [comment]
Hi!
This solution
https://github.com/dendronhq/dendron/issues/2208#issuecomment-1017846603
is working
provided that
**`vault` is added to the end block**
in files
dendron.code-workspace
and
dendron.yml
(see below in **Ref**).


**Ref:**
workspace/dendron.code-workspace
```
{
    "folders": [
. . .
        },
        {
            "name": "test",
            "path": "test"
        },
        {
            "path": "vault"
        },
    ],
    "settings": {
        "dendron.rootDir": ".",
. . .
```

workspace/dendron.yml
```
workspace:
    dendronVersion: 0.74.0
    seeds:
        dendron.templates: {}
    vaults:
. . .
        -
            fsPath: test
            remote:
                type: git
                url: 'https://github.com/test/test.git'
            name: test
        -
            fsPath: vault
            sync: sync
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
. . .
```

**Another associated with this problem:**
The remaining 35 repo in these files I have in order to sort the DESC (there was another problem at one time).
```
voothi.sense
voothi.relax
voothi.rebrain.python-docs
voothi.plan
voothi.place
voothi.people
voothi.org
voothi.kb
voothi.inbox
voothi.hobby
voothi.health
voothi.habit
voothi.fin
voothi.env
voothi.buy
voothi.business
voothi.books
voothi
. . .
vault
```
