### ISSUE TITLE
Set title of schema-instance automatically

### ISSUE THREAD

**Issue by MichaBrugger** [dendronhq/dendron#2275]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

It doesn't really matter which schema, but let's imagine this scenario
```yml
version: 1
schemas:
- id: lang
  title: Programming Language
  desc: ''
  parent: root
  namespace: true 
  children:
    - pattern: type
      title: Data Types
``` 
this gives me a schema that I want to apply to all programming language notes I have. now whenever I'd create the note lang.type (e.g. `java.type`) the frontmatter of that note would look something like:
```yml
id: xxx
title: type
desc: ''
``` 

same goes for desc or basically any other field that it is (or could be) inheriting from the schema 

## Describe the solution you'd like ##

I'd like it to look like this:
```yml
id: xxx
title: Data Types
desc: ''
```
