### ISSUE TITLE
Tree View doesn't update when schemas change

### ISSUE THREAD

**Issue by SeriousBug** [dendronhq/dendron#2363]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When a schema is updated in a way that changes which notes match the schema, the tree view doesn't update to show which ones now match the schema.

## To Reproduce

1. Create a schema like the following:
    ```
    version: 1
    imports: []
    schemas:
      - id: recipes
        title: Recipes
        parent: root
        children:
        - id: soups
          title: Soups
          namespace: true
    ```
2. Create notes `recipes.soups.potato` and `recipes.desserts.pudding`
3. Expand `recipes` in the tree view. "Soups" should have a book symbol next to it, and "Desserts" shouldn't.
4. Edit the schema to add desserts like the following:
    ```
    version: 1
    imports: []
    schemas:
      - id: recipes
        title: Recipes
        parent: root
        children:
        - id: soups
          title: Soups
          namespace: true
        - id: desserts
          title: Desserts
          namespace: true
    ```
5. "Desserts" still will not be highlighted in the tree view with the book symbol
6. Reload the window. "Desserts" will now be highlighted with the symbol

## Expected behavior

The tree view should update when schemas change as well.

## Desktop (please complete the following information)

- Version: 0.80.3
