### ISSUE TITLE
A schema reloading breaks lookup

### ISSUE THREAD

**Issue by SeriousBug** [dendronhq/dendron#2364]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When a schema containing inline children, a pattern, and a x-vault template reloads; lookup completely breaks.

## To Reproduce

1. Clone the dendron-docs repo, and create a schema "rfc"
2. Copy the following contents to schema:
    ```
    version: 1
    schemas:
      - id: rfc
        title: RFC
        parent: root
        children:
          - pattern: "+([0-9])-+([!])" # starts with 1 or more digits, a dash, then one or more characters
            template: dendron://dendron.docs/templates.rfc
    ```
3. Reload the window
4. Run lookup and search for `rfc`, the lookup will work
5. Change something in the schema like the title, and save
6. Run lookup again and search for `rfc`, the lookup stops updating
7. Reload the window again
8. Run lookup again and search for `rfc`, lookup will work once again

## Expected behavior

Lookup should continue to function

## Screenshots

https://www.loom.com/share/a69ac60099694c669016c07b1c6a51a6

## Desktop (please complete the following information)

- OS: Linux
- Version: 0.80.3
