### ISSUE TITLE
Daily template stopped working

### ISSUE THREAD

**Issue by ccamara** [dendronhq/dendron#2439]
I used to have a template for daily journals, but they have suddenly stopped working.

This is my `daily.schema.yml` file:

```yml
version: 1
schemas:
- id: daily
  title: daily
  desc: ""
  parent: root
  children:
    - journal
- id: journal
  title: journal
  desc: ""
  parent: root
  children:
    - year
- id: year
  title: year
  pattern: "[0-2][0-9][0-9][0-9]"
  children: 
    - month
- id: month
  title: month
  pattern: "[0-9][0-9]"
  children: 
    - day
- id: day
  title: day
  pattern: "[0-9][0-9]"
  namespace: true
  template:
    # identifier for the template (for a note based template, it would be the name of the note)
    id: templates.journal.day
    # what sort of template we are creating. currently, only 'note' is supported
    type: note
```

And that's the content of `templates.journal.day.md`:

```markdown
---
id: 1FojTto3kBgykL28KvXHl
title: Day
desc: ''
updated: 1640249265152
created: 1639243152587
---

## Grateful 🙏🏻
 
## Day's goals 🏆

<!-- Add one or two goals you want to do today -->

1. Goal
2. 

## Tasks

- [ ] Item 1

### Next
<!-- Move any incomplete task here. This tasks will be copied in the next day's journal -->
```

Am I missing something? Did I do something wrong?

**Comment by ScriptAutomate** [comment]
Moved this issue from `dendron-site` to here

**Comment by Harshita-mindfire** [comment]
Hey @ccamara , Thanks for reporting the bug. Looks like the attached schema is problematic. You would want to update the parent of `journal` to `daily` instead of `root`
```yml
version: 1
imports: []
schemas:
- id: daily
  title: daily
  parent: root
  children:
    - journal
- id: journal
  title: journal
  parent: root ----> daily
  children:
    - year
  ```
