### ISSUE TITLE
Publish pages in a non-published hierarchy

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#2473]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I have a hierarchy that I do not wish to publish the vast majority of notes within, however there are a few I would like to publish. It used to be possible to have `publishByDefault: false` and then set `published: true` in the frontmatter of individual notes and this would publish just those notes, however the new publishing does not support this. (note the [current new config](https://wiki.dendron.so/notes/WLDbhcr3EHlN3sSquMMLk/) docs still suggest this approach).

## Describe the solution you'd like ##

Similar to previous, the ability to use frontmatter in one note to publish when the default for the hierarchy is set to false.

## Describe alternatives you've considered ##

I haven't tested it but it might be possible to set the hierarchy to publish by default and set the majority of notes to `published: false`

**Comment by hikchoi** [comment]
Hey, thanks for reporting.

Just checked the logic that handles the behavior you are describing, and this hasn't been changed since it was introduced.

This may be a regression from the recent publishing config namespace migration. I'll take a look into this and report back.

I'll also convert this into a `type.bug`. I don't recall any discussions on deprecating the behavior.

**Comment by rlh1994** [comment]
Thanks, I did actually raise as a bug #2463  but closed as thought it was now by design!

**Comment by hikchoi** [comment]
> Thanks, I did actually raise as a bug https://github.com/dendronhq/dendron/issues/2463 but closed as thought it was now by design!

Can you point me to the docs or discussion that made you think it was by design? I don't recall this behavior being deprecated 😅 If the docs are unclear we need to fix that as well.

> This was also the case in 0.82 as well, in case that makes a difference.

Thanks for that extra info. Then it may be another issue.

**Comment by rlh1994** [comment]
> Can you point me to the docs or discussion that made you think it was by design? I don't recall this behavior being deprecated 😅 If the docs are unclear we need to fix that as well.

I can't work out how to link to a specific message in discord (if it's even possible) but I've attached the screenshot.

![Screenshot_20220227-215758](https://user-images.githubusercontent.com/8260415/155901684-790ea6f7-d04d-4a1d-a5d8-2544bda7f3a6.png)

**Comment by kevinslin** [comment]
hey @rlh1994 - looks like I misled you 😅
checked the logic and it should still work.

Given the following notes:

- publish
- nopublish

and this configuration
 
```yml
publishing:
    ...
    hierarchy:
      nopublish:
        publishByDefault: false
    siteHierarchies:
        - root
```

`nopublish` is not published

Can you share your `dendron.yml` where this isn't working?
Also can you confirm whether you are using the latest version of dendron-cli (0.83) and the latest configuration? (v5)

**Comment by rlh1994** [comment]
Sure, the relevant `dendron.yml` part is

```
publishing:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    assetsPrefix: /rh-dendron-notes
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    siteUrl: 'https://an_internal_gitlab.com'
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableRandomlyColoredTags: true
    hierarchy:
        root:
            publishByDefault: true
        daily:
            publishByDefault: false
        tutorial:
            publishByDefault: false
        scratch:
            publishByDefault: false
        user:
            publishByDefault: false
        tags:
            publishByDefault: false
        meeting:
            publishByDefault: false
    writeStubs: false
```

which correctly doesn't publish anything under the `meeting` hierarchy by default. However I have a note `meeting.2022.02.workshop` which was the frontmatter:
```
id: gr9xC7MvVLMSGP8TwzdNl
title: Workshop
desc: ''
published: true
updated: 1645718128219
created: 1645436683107
```
which based on the [docs](https://wiki.dendron.so/notes/WLDbhcr3EHlN3sSquMMLk/) as I understand them should be published, but it isn't.

**Comment by hikchoi** [comment]
@rlh1994 

This is just a hunch, but can you try it like this?:

```yaml
...
    hierarchy:
        # without per-hierarchy config for `root`
        # root:
        #    publishByDefault: true
        daily:
            publishByDefault: false
        tutorial:
            publishByDefault: false
        scratch:
            publishByDefault: false
        user:
            publishByDefault: false
        tags:
            publishByDefault: false
        meeting:
            publishByDefault: false
...
```

**Comment by kevinslin** [comment]
@rlh1994 
Took a deeper look into this . The reason that `meeting.2022.02.workshop` is not publishing:

Our algorithm for publishing for each note:

- frontmatter set `publishing: false` -> no publish
- note is in a vault with `visibility: private` -> no publish
- note in hierarchy where `publishing.hierarchy.{name}.publishByDefault: false` and `publishing: true` not set in note frontmatter ->  no publish

When we export notes for publishing, we go down your hierarchy one level at a time and apply the above algorithm. This means that if **any** of the parent notes end up in `no publish`, we automatically stop traversing the children.

In your case, for the meeting hierarchy, in order for `meeting.2022.02.workshop` to be published, the following notes must exist and must have `publishing` set to `true` in the frontmatter

- meeting
- meeting.2022
- meeting.2022.02

If the intermediate notes don't exist, we default to not publishing. I suspect that somewhere in the above chain, you have a missing note (aka stub)?

**Comment by rlh1994** [comment]
@kevinslin Yeah that's correct, I basically use these as "when required" journal notes so I only have the end note actually created and the rest just comes from the schema. 

Would this be something that could change? I can think of many quite a few cases where I may not want to publish some parents of a hierarchy but might want to publish specific children, including obviously this one! That might cover both cases of the parents not existing at all (so stubs) or where the parents do exist but I don't want their content published.

**Comment by kevinslin** [comment]
Got it. Yeah, this is something we definitely want to improve the UX around. The current behavior is because we want to default to not publishing anything private.

How would you want this UX to work? Say the following situation:

- meeting.md (published: false)
- meeting.2022.02.workshop.md (published: true)

How would you want Dendron to publish this?


Another solution you can do currently is to use the [[collection options|dendron://dendron.dendron-site/dendron.topic.publish-legacy.configuration#collection-options]] property

Set the frontmatter in `meetings.md` as follows
```yml
published: true
has_collection: true
skipLevels: 2
```

This will make sure that the following notes are published

- meeting.md
- meeting.{year}.{month}.{title} (when `published: true`) is set

Whats nice is you get to control exactly the way pages are displayed
