### ISSUE TITLE
"Remove Seed From Workspace" leaves payload value of seed in dendron.yml

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#2479]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When using `Add Seed to Workspace`, a few configuration modifications are made within `dendron.yml`. When you `Remove Seed from Workspace`, it leaves behind the seed template as a vault in `duplicateNoteBehavior` config list for `payload`.

## To Reproduce

1. Clone down https://github.com/dendronhq/seed.dendron.onboarding
1. Check `publishing.duplicateNoteBehavior.payload` values
1. Run `Add Seed to Workspace` command, and add `dendron.templates`
1. See that `dendron.templates` has now been added to `publishing.duplicateNoteBehavior.payload`
1. Run `Remove Seed from Workspace` command, and remove `dendron.templates`
1. See that `dendron.templates` is still in `publishing.duplicateNoteBehavior.payload`

```yml
publishing:
    ...
    ...
    duplicateNoteBehavior:
        action: useVault
        payload:
            - docs
            - vault
            - wiki
            - dendron.templates
```

## Expected behavior

`dendron.templates` should have been removed from payloads when the seed itself was removed from the workspace.

## Desktop (please complete the following information)

- OS: Pop!_OS 21.01
- Versions (all that apply to bug):
  - Dendron Extension: `0.83.0`
  - VS Code version: `1.64.2`
