### ISSUE TITLE
Specifying headers within blocks

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#248]
## Context

Just like how its possible to specify hierarchies with schemas, it should also be possible to specify the header sections within a note.

## Proposal

Extend the existing schema syntax with a `sections` property
```yml
schemas:
- id: foo 
  sections:
    - id: one
      desc: this is a one
    - id: two
    - id: three
```

- foo.md

```markdown

# One 📓 <!-- icon to indicate matching schema -->

# Three 📓

# Four  <!-- no icon-->

```

## Details
- hover over header to see description
- support schema templates on a per section basis
