### ISSUE TITLE
Set default frontmatter from schema

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#253]
## Context

Users should be able to set defaults for properties in their note frontmatter.

## Proposal

Use schemas to deal with frontmatter defaults. Introduce the `attributes` section:

```yml
schemas:
- id: foo
  attributes:
    - id: bar
      default: "a bar"
      scope: note|children|note_and_children
      recursive: true|false
```

To set attributes across all your notes, you can make changes under `root.schema.yml`

- root.schema.yml
```yml
schemas:
- id: root
  attributes:
    - id: bar
      scope: note_and_children
      recursive: true 
      default: "a bar"
```

**Comment by bonnebulle** [comment]
This feature is very usefull.
I try to add [reference_name] as default...
but it's not working.
Here is my settings :
vault/root.schema.yml

```
version: 1
imports: []
schemas:
  - id: root
    attributes:
      - id: bar
        scope: note_and_children
        recursive: true 
        default: "a bar"
    children: []
    title: root
    parent: root
```

When I use lookup creating a _root.test_ note Dendron doesnt add any attribute into my frontmatter.
A clue should realy help me.
At end, I would like to add the reference_name in all my notes (more readable than id)

I also try Schema template

( Thanks for your amazing work )
