### ISSUE TITLE
siteUrl is undefined on publish dev command

### ISSUE THREAD

**Issue by irishandyb** [dendronhq/dendron#2685]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I am having difficulty launching the publish dev server from within vscode. When I launch the dev server via the "Dendron: Publish Dev" command, I first get prompted to select "Use default" or "Use config", I have tried both. After that I am prompted to "Skip" or "Don't skip" the build process. I assume that I should not skip the build process, however I have tried both.
Regardless of the options I choose, I get the following error:

> siteUrl is undefined. See https://dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#siteurl for more details

My dendron.yml file is the default generated file with only the addition of the `siteUrl`.

```yaml
version: 5
dev:
    enablePreviewV2: true
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: true
            vaultSelectionModeOnCreate: smart
            leaveTrace: false
            bubbleUpCreateNew: true
            fuzzThreshold: 0.2
    randomNote: {}
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    copyNoteLink: {}
workspace:
    vaults:
        -
            fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    enableUserTags: true
    enableHashTags: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: false
    enableEditorDecorations: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
preview:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    automaticallyShowPreview: false
publishing:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    copyAssets: true
    siteHierarchies:
        - root
    writeStubs: false
    siteRootDir: build
    siteUrl: "https://test.com"
    seo:
        title: Dendron
        description: Personal Knowledge Space
    github:
        enableEditLink: true
        editLinkText: Edit this page on GitHub
        editBranch: main
        editViewMode: tree
    enableSiteLastModified: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableRandomlyColoredTags: true
    enablePrettyLinks: true
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault
```

However, I am able to build and host the dev via the CLI

$ npx dendron publish build
$ npx dendron publish dev

So it's just within vscode itself that I cannot build. Is there something else that I am missing?

## To Reproduce

1. Fresh install of the Dendron vscode extensions.
2. Initialize a workspace. 
3. Add `siteUrl` to `dendron.yml`
4. Execute the "Dendron: Publish Dev" command.

## Expected behavior

I expect that the dev server be started and available on the configured port.

## Desktop (please complete the following information)

- OS: Windows 10
- Versions (all that apply to bug):
  - Dendron Extension: 0.88.0
  - VS Code version: 1.66.0
  - Dendron CLI: 0.18.0

## Dendron Log file

Attached
[dendron.log](https://github.com/dendronhq/dendron/files/8413758/dendron.log)
