### ISSUE TITLE
Support null front-matter

### ISSUE THREAD

**Issue by alukach** [dendronhq/dendron#2695]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I'm trying to get more familiar with Dendron's [user tags](https://wiki.dendron.so/notes/ESqOqSOEo54lqvGLlQXM6/).  When I create a new user note, I'd like it to be built from a template.  This is easy, I can create a schema + template and we're off.  My template:

```yaml
---
id: fc3kbk6iivs6yyjtpuql2yd
title: User
desc: ""
updated: 1649180005198
created: 1649180005198
social:
  linkedin:
  twitter:
  facebook:
  discord:
  github:
  hn:
  website:
  email:
location:
employer:
---
```

But, when I create the user, all of the blank values are filled in with `null`:

```yaml
---
id: bd4r9ooubx3fzykvfhzw5nj
title: Anthony Lukach
desc: ''
updated: 1649182168569
created: 1649182168569
social:
  linkedin: null
  twitter: null
  facebook: null
  discord: null
  github: null
  hn: null
  website: null
  email: null
location: null
employer: null
---
```

Is there any way to avoid this?  
## Describe the solution you'd like ##

When a note is created from a template with front-matter container empty values, keep them as empty values.

## Describe alternatives you've considered ##

Obviously, I could use some other filler like `''`, but I'd prefer those values to be unfilled rather than pre-populated with `''` or `null`.

## Additional context ##

N/A
