### ISSUE TITLE
Make Edit this page link work with Gitea (and possibly other non-GitHub git hosting)

### ISSUE THREAD

**Issue by KucharczykL** [dendronhq/dendron#2777]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

It is possible to enable showing a link on the bottom of notes to edit that particular note on GitHub, but with GitHub only because of URL differences. With some research and testing, it already works albeit with a small hack:

```yaml
    github:
        enableEditLink: true
        editLinkText: Edit this page on Gitea
        editBranch: branch/main
        editViewMode: src
        editRepository: $DOMAIN/$USER/$REPOSITORY
```

## Describe the solution you'd like ##

Extend the configuration in `dendron.yml` to accomodate other git hosting, e.g. Gitea. I think it is currently impossible for most people to figure out even this hack and if they see `github` as the name of the configuration item, they will think non-GitHub git hosting doesn't work at all.

## Describe alternatives you've considered ##

Keep using the hack or move to GitHub, though I am not on hosting most of my stuff on GitHub primarily because of personal choice.

## Additional context ##

Related to #2776
