### ISSUE TITLE
Error when running dendron publish export (selfcontained)

### ISSUE THREAD

**Issue by joshuajeschek** [dendronhq/dendron#2988]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Publish.  External Site Publish

## Describe the bug

I have a self-contained remote vault (just migrated) and if I run `yarn dendron publish export --target github --yes` I get an error `Cannot read properties of undefined`
After the error occurs, it just hangs and has to be stopped manually to prevent it running indefinitely. 
Look at the end for complete log.

## To Reproduce

I have no idea, I don't know what's wrong.

## Expected behavior

Exporting should work.

## Screenshots

not applicable

## Desktop (please complete the following information)

- OS: Windows and Ubuntu (Desktop and Github Actions)
- Browser (if with published websites; include version): /
- Versions (all that apply to bug):
  - Dendron Extension: /
  - VS Code version: /
  - Dendron CLI: 0.96.0

### The Error
(cleaned up long paths and linebreaks)
```console
yarn dendron publish export --target github --yes
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
⠋ generating metadata for publishing...
⠧ error {"stack":"TypeError: Cannot read properties of undefined (reading 'dendron.defaultTimestampDecorationFormat')
    at Function.getFM (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:123:102)
    at Function._procRemark (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:187:53)
    at Function.procRemarkParse (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:342:21)
    at Function._procRehype (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:284:35)
    at Function.procRehypeFull (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:364:27)
    at NextjsExportPod._renderNote (...\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:174:48)
    at NextjsExportPod.renderBodyToHTML (...\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:278:32)
    at ...\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:334:22
    at arrayMap (...\\node_modules\\lodash\\lodash.js:653:23)
    at Function.map (...\\node_modules\\lodash\\lodash.js:9622:14)","message":"Cannot read properties of undefined (reading 'dendron.defaultTimestampDecorationFormat')"}
{"level":50,"time":1653578126547,"pid":19928,"hostname":"spectre","name":"publish <cmd>","stack":"TypeError: Cannot read properties of undefined (reading 'dendron.defaultTimestampDecorationFormat')
    at Function.getFM (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:123:102)
    at Function._procRemark (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:187:53)
    at Function.procRemarkParse (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:342:21)
    at Function._procRehype (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:284:35)
    at Function.procRehypeFull (...\\node_modules\\@dendronhq\\engine-server\\lib\\markdown\\utilsv5.js:364:27)
    at NextjsExportPod._renderNote (...\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:174:48)
    at NextjsExportPod.renderBodyToHTML (...\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:278:32)
    at ...\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:334:22
    at arrayMap (...\\node_modules\\lodash\\lodash.js:653:23)
    at Function.map (...\\node_modules\\lodash\\lodash.js:9622:14)","type":"Error","msg":"Cannot read properties of undefined (reading 'dendron.defaultTimestampDecorationFormat')"}
unknown error [object Object]
```

### dendron.yml
```yml
version: 5
dev:
    enablePreviewV2: true
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: true
            vaultSelectionModeOnCreate: smart
            leaveTrace: false
            bubbleUpCreateNew: true
            fuzzThreshold: 0.2
    randomNote: {}
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    copyNoteLink: {}
workspace:
    vaults:
        -
            fsPath: .
            remote:
                type: git
                url: https://github.com/joshuajeschek/dendron-tuc
            name: tuc
            selfContained: true
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    enableUserTags: true
    enableHashTags: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: false
    enableEditorDecorations: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    enableFullHierarchyNoteTitle: false
    workspaces: {}
preview:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    automaticallyShowPreview: false
publishing:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    copyAssets: true
    siteFaviconPath: favicon.png
    siteHierarchies:
        - tuc
        - semester
        - betriebssysteme
        - mathematik-iii
        - theoretische-informatik
        - softwareengineering
        - rechnerorganisation
        - mediengestaltung
        # - media-retrieval
    enableSiteLastModified: true
    siteRootDir: docs
    siteUrl: 'https://tuc.jeschek.eu'
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableRandomlyColoredTags: true
    writeStubs: false
    seo:
        title: TUC - Joshua Jeschek
        description: Joshs Uniaufzeichnungen
        author: Joshua Jeschek
    github:
        enableEditLink: true
        editLinkText: Edit this page on GitHub
        editBranch: main
        editViewMode: tree
    enablePrettyLinks: true

```

### dendron.code-workspace
(this should be irrelevant, right?)
```json
{
    "folders": [
        {
            "path": "notes",
            "name": "tuc"
        }
    ]
}

```

## Dendron Log file

not applicable
