### ISSUE TITLE
How to add custom CSS to dendron preview ?

### ISSUE THREAD

**Issue by akharrou** [dendronhq/dendron#3012]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## To Reproduce

Following this doc page: https://wiki.dendron.so/notes/0fbg5vbv5jzb0623pbi4v3t/

I modified `dendron.yml` by adding `theme: custom` under the `preview` field, and added a `custom.css` file with the given example, then reloaded dendron preview and nothing happened.

```
.
├── custom.css
├── dendron.code-workspace
├── dendron.yml
└── notes
    ├── assets
    ├── root.md
    └── root.schema.yml

2 directories, 5 files
```

with the following `dendron.yml`:

```yaml
...
preview:
    theme: custom
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    automaticallyShowPreview: false
...
```

with the following `custom.css`:

```css
body {
  /* The background color of the preview. */
  background-color: #fff;
}

body,
h1,
h2,
h3,
h4 {
  /* Text color for the text, not including links. */
  color: #ffffff;
}

a,
a:hover,
a:active {
  /** Color for links, except ones that have been already visited. */
  color: #b2f7ef;
}
```

## Expected behavior

I expect the preview to change based on the `custom.css`. but instead nothing happens

## Screenshots

![image](https://user-images.githubusercontent.com/36056254/171322050-92aeaf13-13d5-4da2-9545-8a44acfda3b5.png)

## Desktop (please complete the following information)

- OS: MacOS 12.3.1, Darwin x64 21.4.0
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.96.0
  - VS Code version: 
        Version: 1.67.2
        Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
        Date: 2022-05-17T18:20:57.384Z (2 wks ago)
        Electron: 17.4.1
        Chromium: 98.0.4758.141
        Node.js: 16.13.0
        V8: 9.8.177.13-electron.0
  - Dendron CLI:

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/8810850/dendron.log)
