### ISSUE TITLE
Getting 404 when attempt to use the `editLink` on a published note

### ISSUE THREAD

**Issue by taranlu-houzz** [dendronhq/dendron#3074]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When I publish my notes to GitHub pages, the `editLink` does not work. I think this has to do with some slight differences with how dendron is stored within my repo (it is stored at `<repo name>/docs`). Essentially, I am not sure what the correct config would be to allow the `editLink` to function properly. This is my current config related to github:

```yaml
github:
    enableEditLink: true
    editLinkText: Edit this page on GitHub
    editBranch: dev
    editViewMode: tree
    editRepository: "<repo url>"
```
Since I get a 404, I think that the path to the note to edit is incorrect (and the url that it tries to go to does not include the `docs/` dir that should be in the correct path.

## To Reproduce

Specific to my repo setup.

## Expected behavior

The `editLink` should work correctly.

## Desktop (please complete the following information)

- OS: macOS
- Browser (if with published websites; include version): Chrome
- Versions (all that apply to bug):
  - Dendron Extension: v0.98.0
  - VS Code version: 1.67.2
  - Dendron CLI: 0.97.0

**Comment by TysonNguyen** [comment]
> how dendron is stored within my repo (it is stored at <repo name>/docs)

Are you referring inside dendron.yml the `siteRootdir` or the Github pages setting? I am also assuming you followed the publishing guide with [GitHub Pages with GitHub Actions](https://wiki.dendron.so/notes/FnK2ws6w1uaS1YzBUY3BR/) from the Dendron wiki.

I just tested it out the editLink text and it redirects properly to the correct note from the published page.I followed `editRepository: <repo-URL>` similar to [here](https://wiki.dendron.so/notes/l0jasjfkFhVag7c9NQMdY/#editrepository).

**Comment by taranlu-houzz** [comment]
Hi @TysonNguyen, so my repo structure looks like this:
```
- <repo root>
  - docs/
    - vault/
    - dendron.yml
    - <etc.>
  - <other repo dirs, src, etc.>
```

My GitHub pages settings look like this:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/52425255/173400152-3d71b6ad-471f-4bfb-bc02-48c81ce323f2.png">

And this is what my `dendron.yml` looks like:
<details>

```yaml
version: 5
dev:
    enablePreviewV2: true
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: true
            vaultSelectionModeOnCreate: smart
            leaveTrace: false
            bubbleUpCreateNew: true
            fuzzThreshold: 0.2
    randomNote: {}
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    copyNoteLink: {}
workspace:
    vaults:
        - fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    task:
        name: ""
        dateFormat: ""
        addBehavior: childOfCurrent
        statusSymbols:
            "": " "
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: "y"
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    enableUserTags: true
    enableHashTags: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: false
    enableEditorDecorations: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    enableFullHierarchyNoteTitle: false
preview:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    automaticallyShowPreview: false
publishing:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
    copyAssets: true
    siteHierarchies:
        - root
    siteUrl: <hidden because private>
    writeStubs: false
    siteRootDir: docs
    seo:
        title: Dendron
        description: Personal Knowledge Space
    github:
        enableEditLink: true
        editLinkText: Edit this page on GitHub
        editBranch: dev
        editViewMode: tree
        editRepository: <repo url>
    enableSiteLastModified: true
    enableFrontmatterTags: true
    enableHashesForFMTags: false
    enableRandomlyColoredTags: true
    enablePrettyLinks: true
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault

```

</details>

As you mentioned, I followed the publishing guide for [GitHub Pages with GitHub Actions](https://wiki.dendron.so/notes/FnK2ws6w1uaS1YzBUY3BR/) from the wiki (I did have to make some tweaks due to the `<repo/docs/>` difference as I mentioned earlier). The publish action works correctly and updates the pages site, which I am able to visit.
