### ISSUE TITLE
Snapshot PodV1

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#313]
# Snapshot Pod V1

## Goals

Take snapshots of your Dendron Vault in order to revert it back to a given state

## Why

Because data loss can happen. Either user inflicted or platform inflicted. In case [this](https://twitter.com/dendronhq/status/1321458566767669248?s=20) happens again, you'll be able to restore your notes to a known state.

## Details

The V1 phase of the snapshot pod is meant to simply backup/restore your dendron vault. It should be able to do this without any third party dependencies (eg. git, rsync, etc) though it's something that should be used if present (phase 2). 

## Proposal

1. [x] Implement the `SnapshotPod` that can backup/restore your vault 
1. [ ] Add `SnapshotPod` as a configurable hook that runs during Dendron's upgrade process

#### Export
```yml
# where to store snapshot
dest: ~/some-storage-path/dendron/
# number of snapshots to keep
numSnapshots: 3
# how to name the snapshot
format: {timestamp}-{dendron version}
includeAssets: true
```

#### Import
```yml
src: ~/some-storage-path/dendron/
# options: 
# - most-recent (default)
# - {timestamp}-{dendron-version}
snapshot: most-recent
# take a snapshot of the current vault before importing 
snapshot-current: true 
includeAssets: true
```

## Next
1. Use incremental snapshots (eg. `git`, `rsync`)
1. Snapshot (export) individual files and hierarchies
1. Restore (import) individual files and hierarchies
1. Options for remote snapshot
