### ISSUE TITLE
Flatten journal notes in tree view

### ISSUE THREAD

**Issue by buxel** [dendronhq/dendron#326]
**Is your feature request related to a problem? Please describe.**
Is it possible to flatten the journal hierarchies in dendron tree view? via schema maybe?

It gets excessive quickly:
```
- journal
    - 2020
        - 01
            - 10
                - sprint
                - feature-x
            - 11
                - review
                - foo
```

Something like this would be useful
```
- journal
    - 2020.01
        - 10.sprint
        - 10.feature-x
        - 11.review
        - 11.foo
```

I could achieve this via manually naming my notes accordingly and using `-` instead of `.` as separator. But this feels and looks somewhat odd.

**Describe the solution you'd like**
Kevin suggested a reasonable approach here:

 > add this as an option in dendron.yml to start off with unless folks want to customize this per-schema.

```yaml
# control how levels are displayed in the tree view
pathDisplayMiddleware: 
    - id: mergeDates
      format: `{YYYY}.{MM}.{DD}`
```
