### ISSUE TITLE
Schema template does not get populated when `namespace: true` is set

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3381]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When a schema is created and a level has both a template and `namespace: true` is set then the notes created at this and all subsequent levels do not get populated with the template. Removing the `namespace: true`  correctly populates the template

## To Reproduce

1. Create a schema file as follows:
    ```
        version: 1
        imports: []
        schemas:
          - id: test
            children: 
              - testing
            title: test
            parent: root
          - id: testing
            pattern: "*"
            title: "testing"
            # namespace: true
            template:
              id: template.test
              type: note
    ```
3. Create some `template.test` with literally anything in it
4. Create a note called `test.test1` - it should be populated with your template
5. Uncomment the namespace line in the schema and save
6. Create a note called `test.test2` and `test.test2.test3` and see neither are populated with the template.

## Expected behavior

Namespace set to true should apply the template to that and all subsequent levels in the namespace

## Desktop (please complete the following information)

- OS: Windows
- Versions (all that apply to bug):
  - Dendron Extension: 0.107.2
  - VS Code version: 1.68.1
  - Dendron CLI: N/A
