### ISSUE TITLE
`Move Selection To` to a non-existent note does not respect `vaultSelectionModeOnCreate` when `alwaysPrompt`

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#3547]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

`Dendron: `Move Selection To` on a link to a non-existent note does not respect `vaultSelectionModeOnCreate` when set to `alwaysPrompt`. It may also not be respecting smart mode if set to that, as I can only confirm testing where it is just creating the note in the vault of the current note context.

## To Reproduce

1. Setup a multi-vault
2. Set the following values in root vault `dendron.yml`

```yml
commands:
    lookup:
        note:
            confirmVaultOnCreate: true
            vaultSelectionModeOnCreate: alwaysPrompt
            leaveTrace: true
workspace:
    enableXVaultWikiLink: true
```

3. Reload window
4. Create a note in one vault
5. Type a sentence: `This is a sentence that is going to be moved!`
6. Highlight and use `Dendron: Move Selection To` to create a new note where the content will be moved to a new note in the other vault, and a `leaveTrace` will place a wikilink to
7. You will see note is created in vault of the current note context without any vault prompt

## Expected behavior

Respect the value set in `vaultSelectionModeOnCreate` to be respected by `Move Selection To`, and not just use the vault of the current note context.

## Desktop (please complete the following information)

- OS: **Pop!_OS 22.04**
- Versions (all that apply to bug):
  - Dendron Extension: **v0.112.0**
  - VS Code version: **v1.71.2**
