### ISSUE TITLE
`Dendron: Move Header` on a link to a non-existent note does not respect when `leaveTrace` is `true`

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#3548]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## To Reproduce

1. Setup a multi-vault
2. Set the following values in root vault `dendron.yml`

```yml
commands:
    lookup:
        note:
            confirmVaultOnCreate: true
            vaultSelectionModeOnCreate: alwaysPrompt
            leaveTrace: true
workspace:
    enableXVaultWikiLink: true
```

3. Reload window
4. Create a note in one vault
5. Create a section with:

```md
## My Content

This is a note!
- Yes
- It
- Is
```

7. With cursor in `## My Content` header, run `Dendron: Move Header` command
8. Have it added to a new note or existing note
9. Notice that content is not replaced with a backlink when moved

## Expected behavior

When `leaveTrace` is `true`, a backlink should replace the header content in the source note. If `enableXVaultWikiLink: true`, have it replaced with an [cross vault link format](https://wiki.dendron.so/notes/wb1k8li6r5kfzhla7p3ty80/).

## Desktop (please complete the following information)

- OS: **Pop!_OS 22.04**
- Versions (all that apply to bug):
  - Dendron Extension: **v0.112.0**
  - VS Code version: **v1.71.2**
