### ISSUE TITLE
More dynamic journal locations

### ISSUE THREAD

**Issue by buxel** [dendronhq/dendron#374]
**Is your feature request related to a problem? Please describe.**
i tend to have journal notes on various levels of my hierarchy so none of the current settings work for me right away - i always have to adjust the note name when creating one via hotkey.

**Describe the solution you'd like**
(blatantly copied from kevin's response on discord)
When creating a journal note with a current opened note, Dendron will create a journal note based on the closest parent/sibling that has a journal schema. If none is found, default to current behavior.

```yaml
schemas:
- id: foo
  children:
    - changelog
    - dev
- id: dev
  children:
    - journal
- id: changelog
  journal: true
- id: journal
  journal: true
```

- when inside foo.blah
    - create journal note -> foo.changelog.{date}

- when inside foo.dev.blah
    - create journal note -> foo.journal.{date}

- when inside foo.hello.blah
    - create journal note -> show quickpick with foo.changelog.{date} and foo.journal.{date} as suggestions

**Describe alternatives you've considered**
define a general journal parent name in settings ("journal") and whenever a journal note gets created, dendron could traverse up the hierarchy until it finds one and place the note there. if there is none, "journal" at root level will be created.
