### ISSUE TITLE
Add settings to Task notes to allow customizing various decorations

### ISSUE THREAD

**Issue by jeep** [dendronhq/dendron#3753]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I want to use task notes to get some of the decorations that come with them, but I despise the added checkbox and don't like the forced order

## Describe the solution you'd like ##

Add the following options (or similar) to the dendron.yml task section.
```
Decorations:
    status: [checkbox | hide | symbolOnly]
    statusPrefix: [ useBrackets | stringValue ]
    dueDate: [format_str | hide ]
    dueDatePrefix: [stringValue (default: due:)]
    owner: [display | hide]
    ownerPrefix: [stringValue (default: @)]
    priority: [display | hide]
    priorityPrefix: [stringValue (default: prio {I think it should be just pri, but...})
    size: [on | off]
    sizePrefix: [stringValue (default: #size.)
DecorationOrder: [status, link, dueDate, owner, priority, size]
```
There are many ways to control this configuration. I don't think I have a strong preference on how, but those are the things I know I would like to be able to control.

Alternatively, you could add it to the existing fields: statusSymbols, taskCompletStatus, prioritySymbols (is there one for size?), but I feel like controlling both the values and the behaviors in the same place could be difficult to understand. 

Another option is to remove the requirement for them to exist and then by deleting "statusSymbols" I could indicate that I do not want the status to be displayed.
