### ISSUE TITLE
selfContained vaults: Unable to use alternate git branch on remote selfContained vault

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#3778]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When using selfContained vaults, users are unable to add remote git vaults with branches different from the default branch. Instead of `master` or `main`, someone may want to use a different target branch.

## To Reproduce

1. Initialize a new vault
2. Close out Dendron
3. Add the following to `dendron.yml` under `workspace.vaults`:

```yml
        -
            fsPath: dependencies/github.com/ScriptAutomate/dendron-site
            selfContained: true
            remote:
                type: git
                branch: convert-to-selfcontained
                url: >-
                    git@github.com:ScriptAutomate/dendron-site.git
            name: dendron.dendron-site
```

4. Add the following to `folders` in `dendron.code-workspace`:

```json
        {
            "path": "dependencies/github.com/ScriptAutomate/dendron-site/notes",
            "name": "dendron.dendron-site"
        },
```

5. Open Dendron
6. See failure
7. In terminal: Run `cd dependencies/github.com/ScriptAutomate/dendron-site/`
8. Run `git checkout convert-to-selfcontained`
9. Run VSCode command: `Developer: Reload Window`
10. See that it now successfully loads because it is properly referencing the correct branch

## Expected behavior

That either `branch` or `ref` should work inside of multi-vault when it comes to pulling down remote vaults. One of them should be selected by Dendron as the way to work with different branches from a target.

- `ref` seems more universally used in other tools (ex. pre-commit, etc.)
- `branch` is what is referenced in documentation for multi-vault scenarios: https://wiki.dendron.so/notes/45cfb9f2-46cf-4f67-a41e-834818fbd06e/#configuration

## Desktop (please complete the following information)

- OS: Pop!_OS 22.04
- Versions (all that apply to bug):
  - Dendron Extension: `v0.117.0`
  - VS Code version: `v1.73.1`
