### ISSUE TITLE
Self contained vaults should support downloading transitive dependency vaults

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#3792]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the feature/enhancement

[Self Contained Vaults](https://wiki.dendron.so/notes/o4i7a81j778jyh7wql0nacb/) should be aware of the full vault dependency tree when Dendron is initialized. In [RFC 42: Self Contained Vaults](https://docs.dendron.so/notes/aOOBYTowLEKJDEtLWFiHb/), one type of vault dependency are transitive dependencies:

> **Transitive dependency**: If vault "A" depends on vault "B", and vault "B" depends on vault "C", then "A" has a transitive dependency on "C".
> ...
> ...
> Dendron, during initialization, will pull in any vaults that this vault depends on, whether directly or transitively. These vaults should be stored in a dependencies folder inside this vault. All direct and transitive dependencies are flattened into the dependencies vault. If more than one vault depends on the same vault (has the same remote and same target) then the vault will be pulled in only once. The dependencies folder will not be included in git repositories. The dependencies folder is structured like this:
> 
> ```
> dependencies
>├── github.com
>│  ├── dendronhq
>│  │  ├── dendron-docs@main      # depends on github.com/dendronhq/dendron-docs, on main branch
>│  │  └── dendron-site@master    # depends on github.com/dendronhq/dendron-site, on master branch
>│  └── SeriousBug
>│     └── recipes@main  # depends on github.com/SeriousBug/recipes, on main branch
>├── gitlab.com
>│  └── example
>│     └── vault@main             # depends on gitlab.com/example/vault, on main branch
>└── localhost                    # a local vault
 >  └── secret-diary
> ```

Transitive dependencies are ignored at the moment, and only explicitly listed dependency vaults are respected.

## To Reproduce

1. Initialize three vaults and add them all into GitHub as remote git repos
    1. vault1 (by itself, no dependency)
    2. vault2 (a vault with vault1 as an added, remote git vault dependency)
    3. vault3 (a vault with vault2 as an added, remote git vault dependency)  
2. Look at vault3's `dependencies/*` subdir, and see that `vault2` is present (due to being explicitly listed) but `vault1` is missing (a transitive dependency)

## Expected behavior

Transitive dependencies on vaults should be pulled into the `dependencies/*` subdir and flattened, as documented in the docs excerpt in this issue.

It would likely be nice to include this as an option for vaults with `selfContained: true`, that has a value defaulting to `true`.

```yaml
# Example
workspace:
    vaults:
        -
            fsPath: dependencies/github.com/DocsGarden/dg.aws.cli
            selfContained: true
            name: dg.aws.cli
            remote:
                type: git
                url: >-
                    git@github.com:DocsGarden/dg.aws.cli.git
            # An option here? Or in the remote dictionary?
            # Ideas:
            # - includeTransitiveVaults
            # - includeDependencies
            # - includeTransitiveDependencies
            # Not sure which is clearest
            includeDependencies: true 
```
