### ISSUE TITLE
Note template declarations in schema

### ISSUE THREAD

**Issue by Whil-** [dendronhq/dendron#61]
**Is your feature request related to a problem? Please describe.**
Not related to a problem really, but it can be formulated from that perspective anyhow. Something like this: When I create a new note that is of a certain type I'd like to do that with a structure for that type.

**Describe the solution you'd like**
I'd like to be able to specify templates in the {name}.schema.yml files so that the templates can be picked up and used when creating new notes of that certain type.

**Describe alternatives you've considered**
Not considered any alternatives.

**Additional context**
This could be used also for what you call scratch files and journal files. So that scratch files and journal files would be normal types described in schemas but with predefined templates. Maybe something similar is already in use, but I haven't studied dendron enough to know! =)

**Sidenote**: interesting project!

**Comment by kevinslin** [comment]
Hey Whil,

Thanks for the issue. I think this would be a great addition to schemas. A few people have brought up the idea now and it's something we're definitely going to implement. 

Right now, the idea is to add it as a `template` field under schemas which will expand into a vscode snippet of the same name. Only caveat is namespace nodes as they could refer to the namespace or an entity within the namespace (eg. `cli` or `cli.tar`). Thinking right now is for `template` to apply to the namespace entity and not have templates for namespace nodes at the present. Thoughts?

```yml
- id: cli
  desc: command line interface reference
  parent: root
  data: 
    template: cli.temp
    namespace: true
  children:
    - cmd
    - env
- id: env
  desc: variables relevant for command
  data:
    template: cli.env
- id: cmd
  desc: subcommands 
  data: 
    namespace: true
```

**Comment by Whil-** [comment]
Hi,

Regarding vscode snippets; I would rather use another note as template. Possibly a note within a potential template-namespace. ;)

Regarding types which are declared as namespaces; What you write makes sense at the outset. I.e. to let the template be used only for the entities within the namespace, if the type is also a namespace. Might be that it will turn out to limit functionality in the future though. Shortcuts like this usually comes back to bite later on. While I can't come up with a good use case for where it's _needed_ right now, it would at least be needed for completeness. Else ambiguities are introduced.

Slightly of topic:
Regarding the `data:` node; I don't really see why this node is needed. Probably my lack of understanding of the schema design. But to continue anyhow: given how you've put `template:` inside `data:` for both `id: cli` and `id: env` types makes me think `data:` either is not needed or something is ... wrong? Why not let template be a node on the same level in the hierarchy as `id:` and `desc:`? (Same question applies for the need of `namespace:` to be within `data:`, but that's slightly of topic in this context I suppose.)

**Comment by kevinslin** [comment]
Got it. To support that use case, would probably use an object field for templates instead of a scalar. This also helps with handling namespaces. 

```yml
template:
  id: cli.temp
  source: snippet # values: snippet|note
  namespace: true # optional, by default, false. if set to true, applies to the namespace 
```

The simple case would parse the template as a scalar with a default `source`. But going to hold off on the scalar option until we get a feel for what people like to use. 

As far as shortcuts, I agree they can come back and bite you. I also think there's a difference between a **bad** shortcut which takes on hidden technical debt with only minor time savings vs a **good** shortcuts, a deliberate acceptance of some technical debt for a justifiable goal. Since Dendron is just a seed right now, I'm taking a lot of shortcuts to prioritize high impact work. And I leave it to good people like you to tell me when I need to come back and finish a thing 😉

And in regards to the `data` node, it's not the most elegant. The reason it's like that is because both `notes` and `schemas` share a common `node` data and the `data` field holds all attributes unique to the particular node type. Was holding off on cleaning up the syntax until someone brought it up. But since you did -> https://github.com/dendronhq/dendron/issues/63

Will be doing a bunch of work improving schemas this week and next so expect to see some changes soon!
