### ISSUE TITLE
Journal Sibling navigation does not cross month threshold

### ISSUE THREAD

**Issue by Cmhorn** [dendronhq/dendron#688]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

When navigating the first journal entry of a new month, the error: "One is the loneliest number. This node has no siblings :(" is displayed. 

## To Reproduce

1. Over time, use Ctrl+SHIFT+I to create journal entries across month threshold
2. Navigate via Ctrl+SHIFT+] or Ctrl+SHIFT+[
3. See error

## Expected behavior

On the first day of the month, the shortcut navigates back to the last entry of last month. 

## Desktop (please complete the following information)

- OS: PopOs 20.10
- Browser: Firefox
- Version .39

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by flammehawk** [comment]
Currently, this is the intended behavior. 
Since the `GoToSiblingCommand` is intended to navigate the siblings in the current hierarchy. 

In this case, the siblings would be the children of the Current Month you are in. 

For example, you have the following files:
```
journal.2020.01.{01 - 31}.md
journal.2020.02.{01- 28}.md
```
(expand the curly brackets into files with a value in between the two values)

In this case, you would navigate through every child of the hierarchy `journal.2020.01.*` or `journal.2020.02.*`
Making the command work as intended, but this could be optimized for Notes that are part of a Date based hierarchy. 
Allowing you to navigate through the Days / Months / and years. 

We should either improve the current command to detect if we are in a Date based hierarchy or create a new command that is meant for DateBased Hierarchy navigation. 

The only thing that would need to be considered what type of behavior we want if we have the following hierarchy 
```
pro.a.journal.2020.{month}.{day}.tasks.md
pro.a.journal.2020.{month}.{day}.meetings.md
pro.a.journal.2020.{month].{day}.reports.md
```
If we take this as an example, and we are inside the `pro.a.journal.2020.01.01.tasks.md`, and we execute the command to navigate to the next sibling.
Should this next sibling be `pro.a.journal.2020.01.02.tasks.md` or should it be `pro.a.journal.2020.01.01.meetings.md`, or should this be configurable through command args? 

This consideration is only needed if we want to have one command that handles this. If we have two, it would be clearly separated what command does. The Date based one would go to `pro.a.journal.2020.01.02.tasks.md`, and the current one would go to `pro.a.journal.2020.01.01.meetings.md`

**Comment by Cmhorn** [comment]
It comes down to the definition of sibling. Sibling nodes are typically considered nodes on the same hierarchical level under the same parent node.

In your example, 
```
pro.a.journal.2020.{month}.{day}.tasks.md
pro.a.journal.2020.{month}.{day}.meetings.md
pro.a.journal.2020.{month].{day}.reports.md
```
are all siblings. So navigating back from `.reports.md `leads to `meetings.md` which leads to` tasks.md`. 

Because the dates are dot structured, then there is a counter intuitive issue where dates in different months and are therefore no longer siblings. The issue isn't with the notion of the command and siblings, but rather with considering dates as hierarchies in a node tree. 

It is a good observation that dates in this exploded structure landing anywhere in the hierarchy will break the sibling relationship across month and year transitions. 

It would suggest that there may be the need for special case handling to accommodate expectations around dates which are conceptual siblings, but not hierarchical siblings.

**Comment by flammehawk** [comment]
One solution could be to introduce a way to define multiple Segments of a dotted filename as one hierarchy level.
```yml
schemas:
- date:{
   title: "Date: $year $month $day" // eventuel formating options
   type: segments
   pattern: "$year.$month.${month.children['day'].value}"
   segments:
     - year:
          pattern: // pattern of a valid year 
     - month:
          title: "$elementValue"
          type: group
          elements:
              - january: 
                    title: "Januar"
                    pattern: "01"// pattern could include every way to write the month maybe.
                    children: 
                      - day:
                        pattern: "0[1-9]|[1-2][0-9]|3[0-1]" // valid pattern of days for january 
               - ... // other valid month schemas     
}
``` 

If we could have schemas that are like the one I wrote as an example, we could probably improve the navigation for the sibling command to go to the `next` or `previous` date. 
As well as provide different ways of visualization of this for the TreeView / GraphView
