### ISSUE TITLE
Lookup doesn't show completions for a hierarchy with schema

### ISSUE THREAD

**Issue by vicrdguez** [dendronhq/dendron#736]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Having a hierarchy decorated with a schema, there is no completions showing expected children.
I find this issue when I'm more than 2 level deep in a hierarchy, but the schema defines potential childrens:
```yaml
# --- dev
- id: dev
  desc: "dev stuff"
  children:
    - dev.lib
    - migration
    - mode
```

## To Reproduce

1. Create a schema for a hierarchy where you define children more than 2 levels deep
2. Launch the Lookup for and search for that hierarchy
3. Beyond the second level there is no completions

## Expected behavior

The lookup shows completions for a hierarchy with schema, no matter how deep you are in the hierarchy

## Screenshots

For 2 level deep. Lookup shows completions of expected children even when they don't exists as a note yet
![image](https://user-images.githubusercontent.com/52254255/118536005-7a774880-b74b-11eb-83e9-eef1ff6e892e.png)

In the former picture most of the notes don't exist.

Beyond that point, I loose completions:
![image](https://user-images.githubusercontent.com/52254255/118536253-c9bd7900-b74b-11eb-94db-08d759c1e1ba.png)

## Desktop (please complete the following information)

- OS: Arch Linux (Manjaro)
- Version: v41

**Comment by flammehawk** [comment]
Question do you have entries for `migration` and `mode` 

```yml
schemas: 
# --- dev
- id: dev
  desc: "dev stuff"
  children:
    - dev.lib
    - migration
    - mode
- id: migration
- id: mode
```
Secondly, is `dev.lib` a schema that gets imported?
