### ISSUE TITLE
Expand the power of schemas with actions

### ISSUE THREAD

**Issue by xeor** [dendronhq/dendron#745]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I would save a lot of time if I didn't haveto look for the correct schema.

## Describe the solution you'd like ##

Schemas should be actionable so I can trigger a new note creation based on the schema-name and the different children inside. An action should trigger a new note based on the schema config.

Example, if the schema is excended like this:

```
version: 1
schemas:
- id: journal
  desc: Journal notes
  action:
    variables:
      - name: "name"
         type: "text"
         default: ""
         msg: "What should the note suffix be?"
    # Must match pattern
    name: "journal.%Y.%M.%D $name$"
```

will ask for the note name, then create a new note named "journal.2021.05.20 some typed note name"..

Triggering this can be done by a new command (like `Dendron: Lookup Schema`), but that triggers the action, instead of displaying the schema itself.

## Describe alternatives you've considered ##

Making a plugin or abusing the new createHook
